### ISSUE TITLE
App not working after compile in AVD device 

### ISSUE THREAD

**Issue by spyexe** [DrKLO/Telegram#1018]
Hello how are you when I compile and open virtual device after app begin install it said app has stopped when I degug the problem this is the crash show for me what is the solution 
--------- beginning of crash
04-17 13:14:08.201    2575-2575/org.telegram.messenger E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.telegram.messenger, PID: 2575
    java.lang.RuntimeException: Unable to resume activity {org.telegram.messenger/org.telegram.ui.IntroActivity}: java.lang.IllegalArgumentException: App ID length must be 32 characters.
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2951)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2982)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.IllegalArgumentException: App ID length must be 32 characters.
            at net.hockeyapp.android.utils.Util.sanitizeAppIdentifier(Util.java:144)
            at net.hockeyapp.android.CrashManager.initialize(CrashManager.java:347)
            at net.hockeyapp.android.CrashManager.register(CrashManager.java:124)
            at net.hockeyapp.android.CrashManager.register(CrashManager.java:112)
            at org.telegram.messenger.Utilities.checkForCrashes(Utilities.java:761)
            at org.telegram.ui.IntroActivity.onResume(IntroActivity.java:239)
            at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1241)
            at android.app.Activity.performResume(Activity.java:6023)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2940)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2982)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
04-17 13:14:12.405    2575-2575/org.telegram.messenger I/Process﹕ Sending signal. PID: 2575 SIG: 9
04-17 13:14:13.615    2642-2642/org.telegram.messenger W/ResourcesManager﹕ Asset path '/system/framework/com.google.android.maps.jar' does not exist or contains no resources.
04-17 13:14:13.722    2642-2654/org.telegram.messenger W/art﹕ Suspending all threads took: 6.039ms
04-17 13:14:14.277    2642-2668/org.telegram.messenger E/ActivityThread﹕ Failed to find provider info for com.teslacoilsw.notifier

**Comment by DrKLO** [comment]
App ID length must be 32 characters.
Fill APP ID from HockeyApp, or remove HockeyApp from code.
