### ISSUE TITLE
Application not running on 64bit devices

### ISSUE THREAD

**Issue by ShaiBer** [DrKLO/Telegram#1063]
Hi, when I try to run the apk from Google Play it successfully runs on 64 bit devices, but when I compile it myself then it doesn't, and throws the following error: 
"java.lang.UnsatisfiedLinkError: No implementation found for int org.telegram.SQLite.SQLiteDatabase.opendb(java.lang.String, java.lang.String) (tried Java_org_telegram_SQLite_SQLiteDatabase_opendb and Java_org_telegram_SQLite_SQLiteDatabase_opendb__Ljava_lang_String_2Ljava_lang_String_2)
at org.telegram.SQLite.SQLiteDatabase.opendb(Native Method)
at org.telegram.SQLite.SQLiteDatabase.<init>(SQLiteDatabase.java:25)
at org.telegram.android.MessagesStorage.openDatabase(MessagesStorage.java:101)
at org.telegram.android.MessagesStorage.<init>(MessagesStorage.java:77)
at org.telegram.android.MessagesStorage.getInstance(MessagesStorage.java:68)
at org.telegram.android.MediaController.newDownloadObjectsAvailable(MediaController.java:695)
at org.telegram.android.MediaController.checkAutodownloadSettings(MediaController.java:581)
at org.telegram.android.MediaController$2.onReceive(MediaController.java:440)
at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:947)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:145)
at android.app.ActivityThread.main(ActivityThread.java:6141)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)"

Any idea why that happens (on 64 bit devices it works perfectly)?

Thanks!

**Comment by DrKLO** [comment]
And it shouldn't. Native code is not optimized for 64bit. No plans for it for now.

**Comment by ShaiBer** [comment]
Hi, @DrKLO , thanks for the reply, but there are 2 things I don't understand:
1. Why the version in Google Play does work, but the version I compile from GitHub doesn't (I used the latest 2.8.1 from the dev branch). Do you compile in some special way?
2. Why no plan to support 64 bit? all new devices (Samsung S6, HTC One 9, etc.) are 64 bit.

Thanks

**Comment by DrKLO** [comment]
1. Because play store version doesn't have 64bit support. You should check application.mk at this line APP_ABI := armeabi armeabi-v7a x86.
2. Because it will take too much time to rewrite native code.

**Comment by ShaiBer** [comment]
OK, thanks, makes sense.

**Comment by chbaloch** [comment]
@ShaiBer please solve this error.
i import telegram with aniways with android-sdk but showing this error.
![error](https://cloud.githubusercontent.com/assets/10077500/7483216/2df09b42-f38e-11e4-9110-30d24374fe88.jpg)

**Comment by chbaloch** [comment]
@ShaiBer 
I downloaded Aniways SDK (aniways_android_sdk_v2_3_08)
There is 5 folders
1- android-support-v7-appcompat
2- android-support-v7-gridlayout
3- AniwaysResourcesProject
4- cardview
5- libs

I copy libs to \TMessagesProj\libs
i rename AniwaysResourcesProject to Android-SDK

now what should i do these three folders?
1- android-support-v7-appcompat
2- android-support-v7-gridlayout
4- cardview

waiting for anwser
