### ISSUE TITLE
Info on compilation

### ISSUE THREAD

**Issue by tsubus** [DrKLO/Telegram#1065]
In the latest release (2.8.1), when I build the app myself, the "Send Location" makes the app crash as soon as I touch the map to move the cursor around. This happens only on Lollipop 5.1 and on custom ROMs (which probably have StrictMode enabled), it doesn't happen on any other version of Android (but the same thing worked fine on the same device/android version with 2.7.0). If I don't move the map around (or resize the foursquare list of POI, which resizes the map), it doesn't crash and I am able to see my location correctly, and I'm also able to select one of the POI's from Foursquare (and it sends the location just fine, also).

The thing is, when using the official Telegram app from the Play Store, this doesn't happen, so I am wondering if you've done anything differently in the code and haven't published it or if it's possible to know exactly which versions of the SDK/PlayServices/... libraries you're using. Also, I'm building with gradle, are you?

I hope you can help me out with some tips, so I can solve this issue. Here is a logcat of the error:

```
D/StrictMode(12339): Wrote violation #0 of 5: 20320 bytes
D/Error   (12339): ERR: exClass=android.os.StrictMode$StrictModeDiskReadViolation
D/Error   (12339): ERR: exMsg=policy=903 violation=2
D/Error   (12339): ERR: file=StrictMode.java
D/Error   (12339): ERR: class=android.os.StrictMode$AndroidBlockGuardPolicy
D/Error   (12339): ERR: method=onReadFromDisk line=1137
D/Error   (12339): ERR: stack=android.os.StrictMode$StrictModeDiskReadViolation: policy=903 violation=2
D/Error   (12339): 	at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1137)
D/Error   (12339): 	at android.database.sqlite.SQLiteConnection.applyBlockGuardPolicy(SQLiteConnection.java:1043)
D/Error   (12339): 	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:844)
D/Error   (12339): 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
D/Error   (12339): 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
D/Error   (12339): 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
D/Error   (12339): 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
D/Error   (12339): 	at android.database.CursorToBulkCursorAdaptor.getBulkCursorDescriptor(CursorToBulkCursorAdaptor.java:145)
D/Error   (12339): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:122)
D/Error   (12339): 	at android.os.Binder.execTransact(Binder.java:446)
D/Error   (12339): # via Binder call with stack:
D/Error   (12339): android.os.StrictMode$LogStackTrace
D/Error   (12339): 	at android.os.StrictMode.readAndHandleBinderCallViolations(StrictMode.java:1717)
D/Error   (12339): 	at android.os.Parcel.readExceptionCode(Parcel.java:1527)
D/Error   (12339): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:134)
D/Error   (12339): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
D/Error   (12339): 	at android.content.ContentResolver.query(ContentResolver.java:478)
D/Error   (12339): 	at android.content.ContentResolver.query(ContentResolver.java:422)
D/Error   (12339): 	at com.google.maps.api.android.lib6.c.ad.a(Unknown Source)
D/Error   (12339): 	at com.google.maps.api.android.lib6.c.ad.b(Unknown Source)
D/Error   (12339): 	at com.google.maps.api.android.lib6.c.j.<init>(Unknown Source)
D/Error   (12339): 	at com.google.maps.api.android.lib6.c.j.a(Unknown Source)
D/Error   (12339): 	at com.google.maps.api.android.lib6.d.eu.a(Unknown Source)
D/Error   (12339): 	at com.google.maps.api.android.lib6.d.eu.a(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.maps.internal.CreatorImpl.b(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.maps.internal.CreatorImpl.a(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.maps.internal.i.onTransact(SourceFile:79)
D/Error   (12339): 	at android.os.Binder.transact(Binder.java:380)
D/Error   (12339): 	at com.google.android.gms.maps.internal.c$a$a.a(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.maps.MapView$b.bi(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.maps.MapView$b.a(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.dynamic.a.a(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.dynamic.a.onCreate(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
D/Error   (12339): 	at org.telegram.ui.LocationActivity.createView(LocationActivity.java:494)
D/Error   (12339): 	at org.telegram.ui.ActionBar.ActionBarLayout.presentFragment(ActionBarLayout.java:612)
D/Error   (12339): 	at org.telegram.ui.ActionBar.ActionBarLayout.presentFragment(ActionBarLayout.java:552)
D/Error   (12339): 	at org.telegram.ui.ActionBar.BaseFragment.presentFragment(BaseFragment.java:156)
D/Error   (12339): 	at org.telegram.ui.ChatActivity$7.onItemClick(ChatActivity.java:666)
D/Error   (12339): 	at org.telegram.ui.ActionBar.ActionBarMenu.onItemClick(ActionBarMenu.java:119)
D/Error   (12339): 	at org.telegram.ui.ActionBar.ActionBarMenuItem$4.onClick(ActionBarMenuItem.java:226)
D/Error   (12339): 	at android.view.View.performClick(View.java:4781)
D/Error   (12339): 	at android.view.View$PerformClick.run(View.java:19873)
D/Error   (12339): 	at android.os.Handler.handleCallback(Handler.java:739)
D/Error   (12339): 	at android.os.Handler.dispatchMessage(Handler.java:95)
D/Error   (12339): 	at android.os.Looper.loop(Looper.java:135)
D/Error   (12339): 	at android.app.ActivityThread.main(ActivityThread.java:5293)
D/Error   (12339): 	at java.lang.reflect.Method.invoke(Native Method)
D/Error   (12339): 	at java.lang.reflect.Method.invoke(Method.java:372)
D/Error   (12339): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
D/Error   (12339): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
D/Error   (12339): # via Binder call with stack:
D/Error   (12339): android.os.StrictMode$LogStackTrace
D/Error   (12339): 	at android.os.StrictMode.readAndHandleBinderCallViolations(StrictMode.java:1717)
D/Error   (12339): 	at android.os.Parcel.readExceptionCode(Parcel.java:1527)
D/Error   (12339): 	at android.os.Parcel.readException(Parcel.java:1496)
D/Error   (12339): 	at com.google.android.gms.common.internal.bt.a(SourceFile:119)
D/Error   (12339): 	at com.google.android.gms.common.internal.as.a(SourceFile:56)
D/Error   (12339): 	at com.google.android.location.internal.GoogleLocationManagerService.a(SourceFile:200)
D/Error   (12339): 	at com.google.android.location.inter
D/Error   (12339): ERR: TOTAL BYTES WRITTEN: 20552
D/StrictMode(12339): Wrote violation #1 of 5: 20592 bytes
D/StrictMode(12339): Wrote violation #2 of 5: 20240 bytes
D/StrictMode(12339): Wrote violation #3 of 5: 18536 bytes
D/StrictMode(12339): Wrote violation #4 of 5: 18320 bytes
F/StrictMode(12339): Stack is too large: numViolations=5 policy=#387 front=	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:844)
F/StrictMode(12339): 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
F/StrictMode(12339): 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
F/StrictMode(12339): 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
F/StrictMode(12339): 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
F/StrictMode(12339): 	at android.database.CursorToBulkCursorAdaptor.getBulkCursorDescriptor(CursorToBulkCursorAdaptor.java:145)
F/StrictMode(12339): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:122)
F/StrictMode(12339): 	at android.os.Binder.execTransact(Binder.java:446)
F/StrictMode(12339): # via Binder call with stack:
F/StrictMode(12339): android.os.StrictMode$LogStackTrace
F/StrictMode(12339): 	at android.os.StrictMode.readAndHandleBinderCallViolations(StrictMode.java:1717)
F/StrictMode(12339): 	at android.os.Parcel.readExceptionCode(Parcel.java:1527)
F/StrictMode(12339): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:134)
F/StrictMode(12339): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
F/StrictMode(12339): 	at android.content.ContentResolver.query(ContentResolver.java:478)
F/StrictMode(12339): 	at android.content.ContentResolver.query(ContentResolver.java:422)
F/StrictMode(12339): 	at com.google.maps.api.android.lib6.c.ad.a(Unknown Source)
F/StrictMode(12339): 	at com.google.maps.api.android.lib6.c.ad.b(Unknown Source)
F/StrictMode(12339): 	at com.google.maps.api.android.lib6.c.j.<init>(Unknown Source)
F/StrictMode(12339): 	at com.google.maps.api.android.lib6.c.j.a(Unknown Source)
F/StrictMode(12339): 	at com.google.maps.api.android.lib6.d.eu.a(Unknown Source)
F/StrictMode(12339): 	at com.google.maps.api.android.lib6.d.eu.a(Unknown Source)
F/StrictMode(12339): 	at com.google.android.gms.maps.internal.CreatorImpl.b(Unknown Source)
F/StrictMode(12339): 	at com.google.android.gms.maps.internal.CreatorImpl.a(Unknown Source)
F/StrictMode(12339): 	at com.google.android.gms.maps.internal.i.onTransact(SourceFile:79)
F/StrictMode(12339): 	at android.os.Binder.transact(Binder.java:380)
F/StrictMode(12339): 	at com.google.android.gms.maps.internal.c$a$a.a(Unknown Source)
F/StrictMode(12339): 	at com.google.android.gms.maps.MapView$b.bi(Unknown Source)
F/StrictMode(12339): 	at com.google.android.gms.maps.MapView$b.a(Unknown Source)
F/StrictMode(12339): 	at com.google.android.gms.dynamic.a.a(Unknown Source)
F/StrictMode(12339): 	at com.google.android.gms.dynamic.a.onCreate(Unknown Source)
F/StrictMode(12339): 	at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
F/StrictMode(12339): 	at org.telegram.ui.LocationActivity.createView(LocationActivity.java:494)
F/StrictMode(12339): 	at org.telegram.ui.ActionBar.ActionBarLayout.presentFragment(ActionBarLayout.java:612)
F/StrictMode(12339): 	at org.telegram.ui.ActionBar.ActionBarLayout.presentFragment(ActionBarLayout.java:552)
F/StrictMode(12339): 	at org.telegram.ui.ActionBar.BaseFragment.presentFragment(BaseFragment.java:159)
F/StrictMode(12339): 	at org.telegram.ui.ChatActivity$7.onItemClick(ChatActivity.java:666)
F/StrictMode(12339): 	at org.telegram.ui.ActionBar.ActionBarMenu.onItemClick(ActionBarMenu.java:119)
F/StrictMode(12339): 	at org.telegram.ui.ActionBar.ActionBarMenuItem$4.onClick(ActionBarMenuItem.java:226)
F/StrictMode(12339): 	at android.view.View.performClick(View.java:4781)
F/StrictMode(12339): 	at android.view.View$PerformClick.run(View.java:19873)
F/StrictMode(12339): 	at android.os.Handler.handleCallback(Handler.java:739)
F/StrictMode(12339): 	at android.os.Handler.dispatchMessage(Handler.java:95)
F/StrictMode(12339): 	at android.os.Looper.loop(Looper.java:135)
F/StrictMode(12339): 	at android.app.ActivityThread.main(ActivityThread.java:5293)
F/StrictMode(12339): 	at java.lang.reflect.Method.invoke(Native Method)
F/StrictMode(12339): 	at java.lang.reflect.Method.invoke(Method.java:372)
F/StrictMode(12339): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
F/StrictMode(12339): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
F/StrictMode(12339): # via Binder call with stack:
F/StrictMode(12339): android.os.StrictMode$LogStackTrace
F/StrictMode(12339): 	at android.os.StrictMode.readAndHandleBinderCallViolations(StrictMode.java:1717)
F/StrictMode(12339): 	at android.os.Parcel.readExceptionCode(Parcel.java:1527)
F/StrictMode(12339): 	at android.os.Parcel.readException(Parcel.java:1496)
F/StrictMode(12339): 	at com.google.android.gms.common.internal.bt.a(SourceFile:119)
F/StrictMode(12339): 	at com.google.android.gms.common.internal.as.a(SourceFile:56)
F/StrictMode(12339): 	at com.google.android.location.internal.GoogleLocationManagerService.a(SourceFile:200)
F/StrictMode(12339): 	at com.google.android.location.internal.GoogleLocationManagerService.a(SourceFile:47)
F/StrictMode(12339): 	at com.google.android.location.internal.b.a(SourceFile:186)
F/StrictMode(12339): 	at com.google.android.gms.common.internal.b.b(SourceFile:556)
F/StrictMode(12339): 	at com.google.android.gms.common.
D/Error   (12339): ERR: exClass=android.util.Log$TerribleFailure
D/Error   (12339): ERR: exMsg=Stack is too large: numViolations=5 policy=#387 front=	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:844)
D/Error   (12339): 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
D/Error   (12339): 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
D/Error   (12339): 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
D/Error   (12339): 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
D/Error   (12339): 	at android.database.CursorToBulkCursorAdaptor.getBulkCursorDescriptor(CursorToBulkCursorAdaptor.java:145)
D/Error   (12339): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:122)
D/Error   (12339): 	at android.os.Binder.execTransact(Binder.java:446)
D/Error   (12339): # via Binder call with stack:
D/Error   (12339): android.os.StrictMode$LogStackTrace
D/Error   (12339): 	at android.os.StrictMode.readAndHandleBinderCallViolations(StrictMode.java:1717)
D/Error   (12339): 	at android.os.Parcel.readExceptionCode(Parcel.java:1527)
D/Error   (12339): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:134)
D/Error   (12339): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
D/Error   (12339): 	at android.content.ContentResolver.query(ContentResolver.java:478)
D/Error   (12339): 	at android.content.ContentResolver.query(ContentResolver.java:422)
D/Error   (12339): 	at com.google.maps.api.android.lib6.c.ad.a(Unknown Source)
D/Error   (12339): 	at com.google.maps.api.android.lib6.c.ad.b(Unknown Source)
D/Error   (12339): 	at com.google.maps.api.android.lib6.c.j.<init>(Unknown Source)
D/Error   (12339): 	at com.google.maps.api.android.lib6.c.j.a(Unknown Source)
D/Error   (12339): 	at com.google.maps.api.android.lib6.d.eu.a(Unknown Source)
D/Error   (12339): 	at com.google.maps.api.android.lib6.d.eu.a(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.maps.internal.CreatorImpl.b(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.maps.internal.CreatorImpl.a(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.maps.internal.i.onTransact(SourceFile:79)
D/Error   (12339): 	at android.os.Binder.transact(Binder.java:380)
D/Error   (12339): 	at com.google.android.gms.maps.internal.c$a$a.a(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.maps.MapView$b.bi(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.maps.MapView$b.a(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.dynamic.a.a(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.dynamic.a.onCreate(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
D/Error   (12339): 	at org.telegram.ui.LocationActivity.createView(LocationActivity.java:494)
D/Error   (12339): 	at org.telegram.ui.ActionBar.ActionBarLayout.presentFragment(ActionBarLayout.java:612)
D/Error   (12339): 	at org.telegram.ui.ActionBar.ActionBarLayout.presentFragment(ActionBarLayout.java:552)
D/Error   (12339): 	at org.telegram.ui.ActionBar.BaseFragment.presentFragment(BaseFragment.java:159)
D/Error   (12339): 	at org.telegram.ui.ChatActivity$7.onItemClick(ChatActivity.java:666)
D/Error   (12339): 	at org.telegram.ui.ActionBar.ActionBarMenu.onItemClick(ActionBarMenu.java:119)
D/Error   (12339): 	at org.telegram.ui.ActionBar.ActionBarMenuItem$4.onClick(ActionBarMenuItem.java:226)
D/Error   (12339): 	at android.view.View.performClick(View.java:4781)
D/Error   (12339): 	at android.view.View$PerformClick.run(View.java:19873)
D/Error   (12339): 	at android.os.Handler.handleCallback(Handler.java:739)
D/Error   (12339): 	at android.os.Handler.dispatchMessage(Handler.java:95)
D/Error   (12339): 	at android.os.Looper.loop(Looper.java:135)
D/Error   (12339): 	at android.app.ActivityThread.main(ActivityThread.java:5293)
D/Error   (12339): 	at java.lang.reflect.Method.invoke(Native Method)
D/Error   (12339): 	at java.lang.reflect.Method.invoke(Method.java:372)
D/Error   (12339): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
D/Error   (12339): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
D/Error   (12339): # via Binder call with stack:
D/Error   (12339): android.os.StrictMode$LogStackTrace
D/Error   (12339): 	at android.os.StrictMode.readAndHandleBinderCallViolations(StrictMode.java:1717)
D/Error   (12339): 	at android.os.Parcel.readExceptionCode(Parcel.java:1527)
D/Error   (12339): 	at android.os.Parcel.readException(Parcel.java:1496)
D/Error   (12339): 	at com.google.android.gms.common.internal.bt.a(SourceFile:119)
D/Error   (12339): 	at com.google.android.gms.common.internal.as.a(SourceFile:56)
D/Error   (12339): 	at com.google.android.location.internal.GoogleLocationManagerService.a(SourceFile:200)
D/Error   (12339): 	at com.google.android.location.internal.GoogleLocationManagerService.a(SourceFile:47)
D/Error   (12339): 	at com.google.android.location.internal.b.a(SourceFile:186)
D/Error   (12339): 	at com.google.android.gms.common.internal.b.b(SourceFile:556)
D/Error   (12339): 	at com.google.android.gms.c
D/Error   (12339): ERR: file=Log.java
D/Error   (12339): ERR: class=android.util.Log
D/Error   (12339): ERR: method=wtf line=291
D/Error   (12339): ERR: stack=android.util.Log$TerribleFailure: Stack is too large: numViolations=5 policy=#387 front=	at android.database.sqlite.SQLiteConnection.executeForCursorWindow(SQLiteConnection.java:844)
D/Error   (12339): 	at android.database.sqlite.SQLiteSession.executeForCursorWindow(SQLiteSession.java:836)
D/Error   (12339): 	at android.database.sqlite.SQLiteQuery.fillWindow(SQLiteQuery.java:62)
D/Error   (12339): 	at android.database.sqlite.SQLiteCursor.fillWindow(SQLiteCursor.java:144)
D/Error   (12339): 	at android.database.sqlite.SQLiteCursor.getCount(SQLiteCursor.java:133)
D/Error   (12339): 	at android.database.CursorToBulkCursorAdaptor.getBulkCursorDescriptor(CursorToBulkCursorAdaptor.java:145)
D/Error   (12339): 	at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:122)
D/Error   (12339): 	at android.os.Binder.execTransact(Binder.java:446)
D/Error   (12339): # via Binder call with stack:
D/Error   (12339): android.os.StrictMode$LogStackTrace
D/Error   (12339): 	at android.os.StrictMode.readAndHandleBinderCallViolations(StrictMode.java:1717)
D/Error   (12339): 	at android.os.Parcel.readExceptionCode(Parcel.java:1527)
D/Error   (12339): 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:134)
D/Error   (12339): 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
D/Error   (12339): 	at android.content.ContentResolver.query(ContentResolver.java:478)
D/Error   (12339): 	at android.content.ContentResolver.query(ContentResolver.java:422)
D/Error   (12339): 	at com.google.maps.api.android.lib6.c.ad.a(Unknown Source)
D/Error   (12339): 	at com.google.maps.api.android.lib6.c.ad.b(Unknown Source)
D/Error   (12339): 	at com.google.maps.api.android.lib6.c.j.<init>(Unknown Source)
D/Error   (12339): 	at com.google.maps.api.android.lib6.c.j.a(Unknown Source)
D/Error   (12339): 	at com.google.maps.api.android.lib6.d.eu.a(Unknown Source)
D/Error   (12339): 	at com.google.maps.api.android.lib6.d.eu.a(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.maps.internal.CreatorImpl.b(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.maps.internal.CreatorImpl.a(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.maps.internal.i.onTransact(SourceFile:79)
D/Error   (12339): 	at android.os.Binder.transact(Binder.java:380)
D/Error   (12339): 	at com.google.android.gms.maps.internal.c$a$a.a(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.maps.MapView$b.bi(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.maps.MapView$b.a(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.dynamic.a.a(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.dynamic.a.onCreate(Unknown Source)
D/Error   (12339): 	at com.google.android.gms.maps.MapView.onCreate(Unknown Source)
D/Error   (12339): 	at org.telegram.ui.LocationActivity.createView(LocationActivity.java:494)
D/Error   (12339): 	at org.telegram.ui.ActionBar.ActionBarLayout.presentFragment(ActionBarLayout.java:612)
D/Error   (12339): 	at org.telegram.ui.ActionBar.ActionBarLayout.presentFragment(ActionBarLayout.java:552)
D/Error   (12339): 	at org.telegram.ui.ActionBar.BaseFragment.presentFragment(BaseFragment.java:159)
D/Error   (12339): 	at org.telegram.ui.ChatActivity$7.onItemClick(ChatActivity.java:666)
D/Error   (12339): 	at org.telegram.ui.ActionBar.ActionBarMenu.onItemClick(ActionBarMenu.java:119)
D/Error   (12339): 	at org.telegram.ui.ActionBar.ActionBarMenuItem$4.onClick(ActionBarMenuItem.java:226)
D/Error   (12339): 	at android.view.View.performClick(View.java:4781)
D/Error   (12339): 	at android.view.View$PerformClick.run(View.java:19873)
D/Error   (12339): 	at android.os.Handler.handleCallback(Handler.java:739)
D/Error   (12339): 	at android.os.Handler.dispatchMessage(Handler.java:95)
D/Error   (12339): 	at android.os.Looper.loop(Looper.java:135)
D/Error   (12339): 	at android.app.ActivityThread.main(ActivityThread.java:5293)
D/Error   (12339): 	at java.lang.reflect.Method.invoke(Native Method)
D/Error   (12339): 	at java.lang.reflect.Method.invoke(Method.java:372)
D/Error   (12339): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
D/Error   (12339): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
D/Error   (12339): # via Binder call with stack:
D/Error   (12339): android.os.StrictMode$LogStackTrace
D/Error   (12339): 	at android.os.StrictMode.readAndHandleBinderCallViolations(StrictMode.java:1717)
D/Error   (12339): 	at android.os.Parcel.readExceptionCode(Parcel.java:1527)
D/Error   (12339): 	at android.os.Parcel.readException(Parcel.java:1496)
D/Error   (12339): 	at com.google.android.gms.common.internal.bt.a(SourceFile:119)
D/Error   (12339): 	at com.google.android.gms.common.internal.as.a(SourceFile:56)
D/Error   (12339): 	at com.google.android.location.internal.GoogleLocationManagerService.a(SourceFile:200)
D/Error   (12339): 	at com.google.android.location.internal.GoogleLocationManagerService.a(SourceFile:47)
D/Error   (12339): 	at com.google.android.location.internal.b.a(SourceFile:186)
D/Error   (12339): 	at com.google.android.gms.common.internal.b.b(SourceFile
D/Error   (12339): ERR: TOTAL BYTES WRITTEN: 43048
D/AndroidRuntime(12339): Shutting down VM
E/AndroidRuntime(12339): FATAL EXCEPTION: main
E/AndroidRuntime(12339): Process: org.telegram.messenger, PID: 12339
E/AndroidRuntime(12339): java.lang.NullPointerException: null reference
E/AndroidRuntime(12339): 	at com.google.android.gms.internal.s.d(Unknown Source)
E/AndroidRuntime(12339): 	at com.google.android.gms.maps.CameraUpdate.<init>(Unknown Source)
E/AndroidRuntime(12339): 	at com.google.android.gms.maps.CameraUpdateFactory.newLatLng(Unknown Source)
E/AndroidRuntime(12339): 	at org.telegram.ui.LocationActivity.positionMarker(LocationActivity.java:792)
E/AndroidRuntime(12339): 	at org.telegram.ui.LocationActivity.access$2200(LocationActivity.java:75)
E/AndroidRuntime(12339): 	at org.telegram.ui.LocationActivity$17.onMyLocationChange(LocationActivity.java:610)
E/AndroidRuntime(12339): 	at com.google.android.gms.maps.GoogleMap$11.b(Unknown Source)
E/AndroidRuntime(12339): 	at com.google.android.gms.maps.internal.m$a.onTransact(Unknown Source)
E/AndroidRuntime(12339): 	at android.os.Binder.transact(Binder.java:380)
E/AndroidRuntime(12339): 	at com.google.android.gms.maps.internal.bm.a(SourceFile:96)
E/AndroidRuntime(12339): 	at com.google.maps.api.android.lib6.d.ax.a(Unknown Source)
E/AndroidRuntime(12339): 	at com.google.maps.api.android.lib6.d.ax.a(Unknown Source)
E/AndroidRuntime(12339): 	at com.google.maps.api.android.lib6.d.ah.run(Unknown Source)
E/AndroidRuntime(12339): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(12339): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(12339): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(12339): 	at android.app.ActivityThread.main(ActivityThread.java:5293)
E/AndroidRuntime(12339): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12339): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(12339): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
```

**Comment by DrKLO** [comment]
E/AndroidRuntime(12339): java.lang.NullPointerException: null reference
E/AndroidRuntime(12339):    at com.google.android.gms.internal.s.d(Unknown Source)
E/AndroidRuntime(12339):    at com.google.android.gms.maps.CameraUpdate.<init>(Unknown Source)
E/AndroidRuntime(12339):    at com.google.android.gms.maps.CameraUpdateFactory.newLatLng(Unknown Source)
E/AndroidRuntime(12339):    at org.telegram.ui.LocationActivity.positionMarker(LocationActivity.java:792)

Can you check latLng at this line CameraUpdate position = CameraUpdateFactory.newLatLng(latLng);?
Is it null?

**Comment by tsubus** [comment]
Thank you for the reply, I inserted some debug code and no, latLng is not null. I think the issue happens when this code is reached (lines 486-487 https://github.com/DrKLO/Telegram/blob/dev/TMessagesProj/src/main/java/org/telegram/ui/LocationActivity.java#L486 ):

```
userLocation.setLatitude(googleMap.getCameraPosition().target.latitude);
userLocation.setLongitude(googleMap.getCameraPosition().target.longitude);
```

Commenting this out makes the app not crash (but of course the new coordinates are not set). Any ideas?

**Comment by tsubus** [comment]
Disabling strict mode in the ROM fixes it, it's enough to add the following 2 lines to /system/build.prop:

```
persist.sys.strictmode.visual=0
persist.sys.strictmode.disable=1
```

This still doesn't explain why it works with the official Telegram app, but as long as it works now, I'm happy.

Thank you for your time, DrKLO

**Comment by DrKLO** [comment]
Maybe it depends on google play services version, I'm using this one
compile 'com.google.android.gms:play-services:3.2.+'
