### ISSUE TITLE
Android 4.+ got error - NoClassDefFoundError: org/telegram/SQLite/SQLitePreparedStatement 

### ISSUE THREAD

**Issue by harleygroupmap** [DrKLO/Telegram#1257]
Have this error with android version 4.+ but still work with adnroid 5.+.

JNI WARNING: JNI method called with exception pending
07-25 15:14:21.245    2553-2553/com.mag.hdmap W/dalvikvm﹕ in Ljava/lang/Runtime;.nativeLoad:(Ljava/lang/String;Ljava/lang/ClassLoader;)Ljava/lang/String; (GetFieldID)
07-25 15:14:21.245    2553-2553/com.mag.hdmap W/dalvikvm﹕ Pending exception is:
07-25 15:14:21.245    2553-2553/com.mag.hdmap I/dalvikvm﹕ java.lang.NoClassDefFoundError: org/telegram/SQLite/SQLitePreparedStatement
07-25 15:14:21.245    2553-2553/com.mag.hdmap I/dalvikvm﹕ at java.lang.Runtime.nativeLoad(Native Method)
07-25 15:14:21.245    2553-2553/com.mag.hdmap I/dalvikvm﹕ at java.lang.Runtime.loadLibrary(Runtime.java:368)
07-25 15:14:21.245    2553-2553/com.mag.hdmap I/dalvikvm﹕ at java.lang.System.loadLibrary(System.java:535)
07-25 15:14:21.245    2553-2553/com.mag.hdmap I/dalvikvm﹕ at org.telegram.android.NativeLoader.initNativeLibs(NativeLoader.java:151)
07-25 15:14:21.245    2553-2553/com.mag.hdmap I/dalvikvm﹕ at org.telegram.messenger.ApplicationLoader.onCreate(ApplicationLoader.java:188)
07-25 15:14:21.245    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
07-25 15:14:21.245    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4115)
07-25 15:14:21.245    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.app.ActivityThread.access$1300(ActivityThread.java:134)
07-25 15:14:21.245    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1285)
07-25 15:14:21.245    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.os.Handler.dispatchMessage(Handler.java:99)
07-25 15:14:21.245    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.os.Looper.loop(Looper.java:154)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.app.ActivityThread.main(ActivityThread.java:4624)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at java.lang.reflect.Method.invokeNative(Native Method)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at java.lang.reflect.Method.invoke(Method.java:511)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at dalvik.system.NativeStart.main(Native Method)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ Caused by:
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ java.lang.ClassNotFoundException: org.telegram.SQLite.SQLitePreparedStatement
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at java.lang.Runtime.nativeLoad(Native Method)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at java.lang.Runtime.loadLibrary(Runtime.java:368)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at java.lang.System.loadLibrary(System.java:535)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at org.telegram.android.NativeLoader.initNativeLibs(NativeLoader.java:151)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at org.telegram.messenger.ApplicationLoader.onCreate(ApplicationLoader.java:188)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4115)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.app.ActivityThread.access$1300(ActivityThread.java:134)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1285)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.os.Handler.dispatchMessage(Handler.java:99)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.os.Looper.loop(Looper.java:154)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.app.ActivityThread.main(ActivityThread.java:4624)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at java.lang.reflect.Method.invokeNative(Native Method)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at java.lang.reflect.Method.invoke(Method.java:511)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at dalvik.system.NativeStart.main(Native Method)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ "main" prio=5 tid=1 NATIVE
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ | group="main" sCount=0 dsCount=0 obj=0x40dc34c0 self=0x10d77b0
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ | sysTid=2553 nice=0 sched=0/0 cgrp=default handle=1074713980
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ | schedstat=( 1201513383 386196772 1522 ) utm=119 stm=1 core=0
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at java.lang.Runtime.nativeLoad(Native Method)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at java.lang.Runtime.loadLibrary(Runtime.java:368)
07-25 15:14:21.246    2553-2553/com.mag.hdmap I/dalvikvm﹕ at java.lang.System.loadLibrary(System.java:535)
07-25 15:14:21.247    2553-2553/com.mag.hdmap I/dalvikvm﹕ at org.telegram.android.NativeLoader.initNativeLibs(NativeLoader.java:151)
07-25 15:14:21.247    2553-2553/com.mag.hdmap I/dalvikvm﹕ at org.telegram.messenger.ApplicationLoader.onCreate(ApplicationLoader.java:188)
07-25 15:14:21.247    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
07-25 15:14:21.247    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4115)
07-25 15:14:21.247    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.app.ActivityThread.access$1300(ActivityThread.java:134)
07-25 15:14:21.247    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1285)
07-25 15:14:21.247    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.os.Handler.dispatchMessage(Handler.java:99)
07-25 15:14:21.247    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.os.Looper.loop(Looper.java:154)
07-25 15:14:21.247    2553-2553/com.mag.hdmap I/dalvikvm﹕ at android.app.ActivityThread.main(ActivityThread.java:4624)
07-25 15:14:21.247    2553-2553/com.mag.hdmap I/dalvikvm﹕ at java.lang.reflect.Method.invokeNative(Native Method)
07-25 15:14:21.247    2553-2553/com.mag.hdmap I/dalvikvm﹕ at java.lang.reflect.Method.invoke(Method.java:511)
07-25 15:14:21.247    2553-2553/com.mag.hdmap I/dalvikvm﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:809)
07-25 15:14:21.247    2553-2553/com.mag.hdmap I/dalvikvm﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
07-25 15:14:21.247    2553-2553/com.mag.hdmap I/dalvikvm﹕ at dalvik.system.NativeStart.main(Native Method)
07-25 15:14:21.247    2553-2553/com.mag.hdmap I/dalvikvm﹕ [ 07-25 15:14:21.247  2553:0x9f9 E/dalvikvm ]
    VM aborting
07-25 15:14:21.247    2553-2553/com.mag.hdmap A/libc﹕ Fatal signal 11 (SIGSEGV) at 0xdeadd00d (code=1)
07-25 15:14:23.800    2553-2556/com.mag.hdmap I/dalvikvm﹕ threadid=3: reacting to signal 3

**Comment by harleygroupmap** [comment]
Fixed: need org.telegram.messenger.ApplicationLoader extends MultiDexApplication.

p.s: plz add this fix in build project!!
