### ISSUE TITLE
Big group Crash

### ISSUE THREAD

**Issue by uira** [DrKLO/Telegram#1268]
We got this message when accidentaly add more than 200 users in a group.

we get this error message:

Method: messages.setTyping
Result: {"_":"rpc_error","error_code":400,"error_message":"PEER_ID_INVALID"}
Stack: Error
    at h (https://web.telegram.org/js/app.js:16:26020)
    at https://web.telegram.org/js/app.js:16:27238
    at l (https://web.telegram.org/js/app.js:8:6393)
    at https://web.telegram.org/js/app.js:8:6565
    at u.$eval (https://web.telegram.org/js/app.js:8:13762)
    at u.$digest (https://web.telegram.org/js/app.js:8:12258)
    at https://web.telegram.org/js/app.js:8:13847
    at s (https://web.telegram.org/js/app.js:7:744)
    at https://web.telegram.org/js/app.js:7:2742
    at n (https://web.telegram.org/js/app.js:2:16525)

**Comment by gomex** [comment]
:+1:

**Comment by chris-redfield** [comment]
Bump

**Comment by gutocarvalho** [comment]
:+1:

**Comment by RatoX** [comment]
+1

**Comment by DrKLO** [comment]
This repo is only about Android client.

**Comment by uira** [comment]
Sorry. In fact, this is a server problem. 

Please, Do you know where we can report this?

**Comment by auchri** [comment]
Twitter: https://twitter.com/telegram
