### ISSUE TITLE
Trying to use a recycled bitmap 

### ISSUE THREAD

**Issue by miuirussia** [DrKLO/Telegram#777]
Bug with latest Telegram v2.3.3 (416). Telegram not starting:
```
01-25 17:22:18.227 16638 16638 E AndroidRuntime: FATAL EXCEPTION: main
01-25 17:22:18.227 16638 16638 E AndroidRuntime: Process: org.telegram.messenger, PID: 16638
01-25 17:22:18.227 16638 16638 E AndroidRuntime: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@4293e448
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.graphics.drawable.LayerDrawable.draw(LayerDrawable.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.View.draw(View.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.View.getDisplayList(View.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.View.getDisplayList(View.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.View.draw(View.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.ViewGroup.drawChild(ViewGroup.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.ViewGroup.dispatchDraw(ViewGroup.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.View.draw(View.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.widget.FrameLayout.draw(FrameLayout.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:2326)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.View.getDisplayList(View.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.View.getDisplayList(View.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.HardwareRenderer$GlRenderer.buildDisplayList(HardwareRenderer.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.HardwareRenderer$GlRenderer.draw(HardwareRenderer.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.ViewRootImpl.draw(ViewRootImpl.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at java.lang.reflect.Method.invokeNative(Native Method)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
01-25 17:22:18.227 16638 16638 E AndroidRuntime: 	at dalvik.system.NativeStart.main(Native Method)
01-25 17:22:18.227   814  1420 W ActivityManager:   Force finishing activity org.telegram.messenger/org.telegram.ui.LaunchActivity
```

**Comment by DrKLO** [comment]
I don't see any calls in this call stack in Telegram code.
Last version was only with this changes: https://github.com/DrKLO/Telegram/commit/2fcef37b9ed73d1bee19eef8b06d73ddd7903274
Something wrong with your android or tweeks you installed.
