### ISSUE TITLE
"IllegalArgumentException: App ID must be 32 characters." when trying to build in Android Studio

### ISSUE THREAD

**Issue by Glaedr** [DrKLO/Telegram#786]
I cloned the project, opened it up in Android Studio, synced Gradle files and tried to build. After copying the default.keystore file from .android (the build process complained about its lack) I'm getting this exception when I try to run the App:
```
java.lang.RuntimeException: Unable to resume activity {org.telegram.messenger/org.telegram.ui.IntroActivity}: java.lang.IllegalArgumentException: App ID length must be 32 characters.
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2951)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2982)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: java.lang.IllegalArgumentException: App ID length must be 32 characters.
            at net.hockeyapp.android.utils.Util.sanitizeAppIdentifier(Util.java:144)
            at net.hockeyapp.android.CrashManager.initialize(CrashManager.java:347)
            at net.hockeyapp.android.CrashManager.register(CrashManager.java:124)
            at net.hockeyapp.android.CrashManager.register(CrashManager.java:112)
            at org.telegram.messenger.Utilities.checkForCrashes(Utilities.java:718)
            at org.telegram.ui.IntroActivity.onResume(IntroActivity.java:231)
            at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1241)
            at android.app.Activity.performResume(Activity.java:6019)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2940)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2982)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2365)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
```
Is the problem known? Am I getting some importing stuff wrong?

**Comment by DrKLO** [comment]
See Readme and BuildVars.java.

**Comment by Glaedr** [comment]
I got an APP ID and filled the fields but it doesn't seem to make any difference, looks like it requires me to fill HOCKEY_APP_HASH too, do I have to be a Hockey App user to build and run this stuff?

**Comment by DrKLO** [comment]
No, you can remove HockeyApp from code. It's for collecting crash reports.

**Comment by roshara** [comment]
I got exactly the same problem, I simply tested for the HOCKEY_APP_HASH length and copied my APP_HASH string to HOCKEY_APP_HASH string. And it worked (:
Just fill up with chars to fit the 32 characters, e.g. md5 hash for "hello" = 5d41402abc4b2a76b9719d911017c592

change
String HOCKEY_APP_HASH = "5d41402abc4b2a76b9719d911017c592";
in
src/main/java/org/telegram/messenger/BuildVars.java
and apps starts fine
