### ISSUE TITLE
Using Genemotion to run 

### ISSUE THREAD

**Issue by EasonWang01** [DrKLO/Telegram#856]
1.I use genemotion to run when I click the telegram icon it says telegram has stop 
{
1000-1000/org.telegram.messenger E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to resume activity {org.telegram.messenger/org.telegram.ui.IntroActivity}: java.lang.IllegalArgumentException: App ID length must be 32 characters.
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2575)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2603)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2089)
            at android.app.ActivityThread.access$600(ActivityThread.java:130)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalArgumentException: App ID length must be 32 characters.
            at net.hockeyapp.android.utils.Util.sanitizeAppIdentifier(Util.java:144)
            at net.hockeyapp.android.CrashManager.initialize(CrashManager.java:347)
            at net.hockeyapp.android.CrashManager.register(CrashManager.java:124)
            at net.hockeyapp.android.CrashManager.register(CrashManager.java:112)
            at org.telegram.messenger.Utilities.checkForCrashes(Utilities.java:718)
            at org.telegram.ui.IntroActivity.onResume(IntroActivity.java:240)
            at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1184)
            at android.app.Activity.performResume(Activity.java:5082)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2565)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2603)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2089)
            at android.app.ActivityThread.access$600(ActivityThread.java:130)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:4745)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
            at dalvik.system.NativeStart.main(Native Method)
}
How can I solve this?
2.
If I want to change the name and remove F&Q which line I should change in DrawerLayoutAdapter.java, SettingsActivity.java  and AndroidManifest.xml?   thanks

**Comment by EasonWang01** [comment]
I Have solve thx

**Comment by onlynight** [comment]
how did you solve this problem, please help me
