### ISSUE TITLE
Problems with telegram

### ISSUE THREAD

**Issue by Nekbakht** [DrKLO/Telegram#908]
I did change package name of telegram but i have this problem : When i run app on emulator app is closing how to need to fix it?
Log list:
03-13 00:17:29.155    9593-9593/org.nekC.messenger E/AndroidRuntime﹕ FATAL EXCEPTION: main
    java.lang.UnsatisfiedLinkError: Native method not found: org.nekC.SQLite.SQLiteDatabase.opendb:(Ljava/lang/String;Ljava/lang/String;)I
            at org.nekC.SQLite.SQLiteDatabase.opendb(Native Method)
            at org.nekC.SQLite.SQLiteDatabase.<init>(SQLiteDatabase.java:25)
            at org.nekC.android.MessagesStorage.openDatabase(MessagesStorage.java:101)
            at org.nekC.android.MessagesStorage.<init>(MessagesStorage.java:77)
            at org.nekC.android.MessagesStorage.getInstance(MessagesStorage.java:68)
            at org.nekC.android.MediaController.newDownloadObjectsAvailable(MediaController.java:692)
            at org.nekC.android.MediaController.checkAutodownloadSettings(MediaController.java:578)
            at org.nekC.android.MediaController$2.onReceive(MediaController.java:437)
            at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:758)
            at android.os.Handler.handleCallback(Handler.java:725)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5041)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:817)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
            at dalvik.system.NativeStart.main(Native Method)

Run list:
Launching application: org.telegram.messenger/org.nekC.ui.LaunchActivity.
DEVICE SHELL COMMAND: am start -n "org.telegram.messenger/org.nekC.ui.LaunchActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.telegram.messenger/org.nekC.ui.LaunchActivity }
Error type 3
Error: Activity class {org.telegram.messenger/org.nekC.ui.LaunchActivity} does not exist.

**Comment by Nekbakht** [comment]
I think problem with ndk or sql

**Comment by DrKLO** [comment]
You should change package name in all native source code and rebuild it.
Java_org_telegram_messenger_
Java_org_telegram_
etc
