### ISSUE TITLE
Crash in update : java.lang.ClassCastException: org.telegram.messenger.TLRPC$TL_chat cannot be cast to org.telegram.messenger.TLRPC$User

### ISSUE THREAD

**Issue by mosqueiro** [DrKLO/Telegram#924]
After updating the apk some devices are getting this crash , but if I reinstall the apk not get the error .
What could it be?
```
03-20 12:21:04.159    2280-2308/org.telegram.messenger E/AndroidRuntime﹕ FATAL EXCEPTION: stageQueue
    java.lang.ClassCastException: org.telegram.messenger.TLRPC$TL_chat cannot be cast to org.telegram.messenger.TLRPC$User
            at org.telegram.messenger.TLRPC$TL_updates_difference.readParams(TLRPC.java:813)
            at org.telegram.messenger.TLClassStore.TLdeserialize(TLClassStore.java:455)
            at org.telegram.messenger.Utilities.decompress(Utilities.java:435)
            at org.telegram.messenger.ConnectionsManager.processMessage(ConnectionsManager.java:2096)
            at org.telegram.messenger.ConnectionsManager.tcpConnectionReceivedData(ConnectionsManager.java:2678)
            at org.telegram.messenger.TcpConnection$9.run(TcpConnection.java:526)
            at android.os.Handler.handleCallback(Handler.java:615)
            at android.os.Handler.dispatchMessage(Handler.java:92)
            at android.os.Looper.loop(Looper.java:137)
            at org.telegram.messenger.DispatchQueue.run(DispatchQueue.java:100)
```

**Comment by DrKLO** [comment]
Did you changed versionCode in build.gradle?

**Comment by mosqueiro** [comment]
Yes I changed.

**Comment by mosqueiro** [comment]
@DrKLO i lacked change :
```
targetSdkVersion 21
```
to
```
targetSdkVersion 22
```
And it worked ! Thanks for your help!

**Comment by DrKLO** [comment]
Did you build debug version or not? I need logs from your device
It's not related to targetSdkVersion

**Comment by DrKLO** [comment]
Is it happened after messages forward?

**Comment by mosqueiro** [comment]
@DrKLO it soon appears in the application start . But I think when I decided to changed the targetSdkVersion did he rebuild the Android Studio.
So it should have solved the problem .
