### ISSUE TITLE
application is closed, will not start

### ISSUE THREAD

**Issue by IB313184** [DrKLO/Telegram#979]
Git downloaded the source, compile and the mobile application is closed, will not start

**Comment by IB313184** [comment]
04-05 17:39:40.544  23302-23302/org.telegram.messenger W/dalvikvm﹕ threadid=1: thread exiting with uncaught exception (group=0x4160c698)
04-05 17:39:40.544  23302-23302/org.telegram.messenger E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.telegram.messenger, PID: 23302
    java.lang.RuntimeException: Unable to resume activity {org.telegram.messenger/org.telegram.ui.IntroActivity}: java.lang.IllegalArgumentException: App ID length must be 32 characters.
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2812)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2841)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2276)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalArgumentException: App ID length must be 32 characters.
            at net.hockeyapp.android.utils.Util.sanitizeAppIdentifier(Util.java:144)
            at net.hockeyapp.android.CrashManager.initialize(CrashManager.java:347)
            at net.hockeyapp.android.CrashManager.register(CrashManager.java:124)
            at net.hockeyapp.android.CrashManager.register(CrashManager.java:112)
            at org.telegram.messenger.Utilities.checkForCrashes(Utilities.java:718)
            at org.telegram.ui.IntroActivity.onResume(IntroActivity.java:240)
            at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1192)
            at android.app.Activity.performResume(Activity.java:5310)
            at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2802)
            at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2841)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2276)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5146)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by IB313184** [comment]
OK !!!

https://github.com/DrKLO/Telegram/issues/786

**Comment by auchri** [comment]
Close the issue please if you fixed your crash
