### ISSUE TITLE
Problem to import telegram to android studio 

### ISSUE THREAD

**Issue by Nekbakht** [DrKLO/Telegram#991]
When i have last windows i workinh with telegram at android studio and save my telegram projects to my flash card but i install another windows and when i import telegram project i have this error
Error:Execution failed for task ':TMessagesProj:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	D:\Android Developer\sdk\build-tools\21.1.2\dx.bat --dex --no-optimize --output C:\Documents and Settings\User\Рабочий стол\Telegram-master\TMessagesProj\build\intermediates\dex\debug --input-list=C:\Documents and Settings\User\Рабочий стол\Telegram-master\TMessagesProj\build\intermediates\tmp\dex\debug\inputList.txt
Error Code:
	1
Output:
	UNEXPECTED TOP-LEVEL EXCEPTION:
	java.lang.RuntimeException: C:\Documents and Settings\User\Р Р°Р±РѕС‡РёР№ СЃС‚РѕР»\Telegram-master\TMessagesProj\build\intermediates\classes\debug: file not found
		at com.android.dex.util.FileUtils.readFile(FileUtils.java:51)
		at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:169)
		at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
		at com.android.dx.command.dexer.Main.processOne(Main.java:632)
		at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
		at com.android.dx.command.dexer.Main.run(Main.java:246)
		at com.android.dx.command.dexer.Main.main(Main.java:215)
		at com.android.dx.command.Main.main(Main.java:106)
	UNEXPECTED TOP-LEVEL EXCEPTION:
	java.io.FileNotFoundException: C:\Documents and Settings\User\Р Р°Р±РѕС‡РёР№ СЃС‚РѕР»\Telegram-master\TMessagesProj\build\intermediates\pre-dexed\debug\support-annotations-22.0.0-188700641ca2f5cd5eba9d6dff95d170412745c9.jar (Системе не удается найти указанный путь)
		at java.util.zip.ZipFile.open(Native Method)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:244)
		at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
		at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
		at com.android.dx.command.dexer.Main.processOne(Main.java:632)
		at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
		at com.android.dx.command.dexer.Main.run(Main.java:246)
		at com.android.dx.command.dexer.Main.main(Main.java:215)
		at com.android.dx.command.Main.main(Main.java:106)
	UNEXPECTED TOP-LEVEL EXCEPTION:
	java.io.FileNotFoundException: C:\Documents and Settings\User\Р Р°Р±РѕС‡РёР№ СЃС‚РѕР»\Telegram-master\TMessagesProj\build\intermediates\pre-dexed\debug\aspectjrt-1.8.2-71f609ac7eefbf8f23598c92fd2e565bac95db68.jar (Системе не удается найти указанный путь)
		at java.util.zip.ZipFile.open(Native Method)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:244)
		at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
		at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
		at com.android.dx.command.dexer.Main.processOne(Main.java:632)
		at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
		at com.android.dx.command.dexer.Main.run(Main.java:246)
		at com.android.dx.command.dexer.Main.main(Main.java:215)
		at com.android.dx.command.Main.main(Main.java:106)
	UNEXPECTED TOP-LEVEL EXCEPTION:
	java.io.FileNotFoundException: C:\Documents and Settings\User\Р Р°Р±РѕС‡РёР№ СЃС‚РѕР»\Telegram-master\TMessagesProj\build\intermediates\pre-dexed\debug\internal_impl-22.0.0-cf0ae709d4f7e0762f800c77eb22969c1711de78.jar (Системе не удается найти указанный путь)
		at java.util.zip.ZipFile.open(Native Method)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:244)
		at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
		at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
		at com.android.dx.command.dexer.Main.processOne(Main.java:632)
		at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
		at com.android.dx.command.dexer.Main.run(Main.java:246)
		at com.android.dx.command.dexer.Main.main(Main.java:215)
		at com.android.dx.command.Main.main(Main.java:106)
	UNEXPECTED TOP-LEVEL EXCEPTION:
	java.io.FileNotFoundException: C:\Documents and Settings\User\Р Р°Р±РѕС‡РёР№ СЃС‚РѕР»\Telegram-master\TMessagesProj\build\intermediates\pre-dexed\debug\HockeySDK-3.5.0-59708b0aaf9d4dde1239126e06af9f6c227a6fdb.jar (Системе не удается найти указанный путь)
		at java.util.zip.ZipFile.open(Native Method)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:244)
		at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
		at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
		at com.android.dx.command.dexer.Main.processOne(Main.java:632)
		at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
		at com.android.dx.command.dexer.Main.run(Main.java:246)
		at com.android.dx.command.dexer.Main.main(Main.java:215)
		at com.android.dx.command.Main.main(Main.java:106)
	UNEXPECTED TOP-LEVEL EXCEPTION:
	java.io.FileNotFoundException: C:\Documents and Settings\User\Р Р°Р±РѕС‡РёР№ СЃС‚РѕР»\Telegram-master\TMessagesProj\build\intermediates\pre-dexed\debug\classes-f25334fd6ab0c91c4dcb115fa0c7cb62e19307d3.jar (Системе не удается найти указанный путь)
		at java.util.zip.ZipFile.open(Native Method)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:244)
		at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
		at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
		at com.android.dx.command.dexer.Main.processOne(Main.java:632)
		at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
		at com.android.dx.command.dexer.Main.run(Main.java:246)
		at com.android.dx.command.dexer.Main.main(Main.java:215)
		at com.android.dx.command.Main.main(Main.java:106)
	UNEXPECTED TOP-LEVEL EXCEPTION:
	java.io.FileNotFoundException: C:\Documents and Settings\User\Р Р°Р±РѕС‡РёР№ СЃС‚РѕР»\Telegram-master\TMessagesProj\build\intermediates\pre-dexed\debug\classes-08f7aba3a4ad1780469eaf679affd91419e764f1.jar (Системе не удается найти указанный путь)
		at java.util.zip.ZipFile.open(Native Method)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:244)
		at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
		at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
		at com.android.dx.command.dexer.Main.processOne(Main.java:632)
		at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
		at com.android.dx.command.dexer.Main.run(Main.java:246)
		at com.android.dx.command.dexer.Main.main(Main.java:215)
		at com.android.dx.command.Main.main(Main.java:106)
	UNEXPECTED TOP-LEVEL EXCEPTION:
	java.io.FileNotFoundException: C:\Documents and Settings\User\Р Р°Р±РѕС‡РёР№ СЃС‚РѕР»\Telegram-master\TMessagesProj\build\intermediates\pre-dexed\debug\isoparser-1.0.6-f9439f93c053425fa0e2ab6e9ad602d87fc93212.jar (Системе не удается найти указанный путь)
		at java.util.zip.ZipFile.open(Native Method)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:244)
		at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
		at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
		at com.android.dx.command.dexer.Main.processOne(Main.java:632)
		at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
		at com.android.dx.command.dexer.Main.run(Main.java:246)
		at com.android.dx.command.dexer.Main.main(Main.java:215)
		at com.android.dx.command.Main.main(Main.java:106)
	UNEXPECTED TOP-LEVEL EXCEPTION:
	java.io.FileNotFoundException: C:\Documents and Settings\User\Р Р°Р±РѕС‡РёР№ СЃС‚РѕР»\Telegram-master\TMessagesProj\build\intermediates\pre-dexed\debug\classes-0d6b4edf2f7d24a44429d647e5c4a74ccca3f0b6.jar (Системе не удается найти указанный путь)
		at java.util.zip.ZipFile.open(Native Method)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at java.util.zip.ZipFile.<init>(Unknown Source)
		at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:244)
		at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
		at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
		at com.android.dx.command.dexer.Main.processOne(Main.java:632)
		at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
		at com.android.dx.command.dexer.Main.run(Main.java:246)
		at com.android.dx.command.dexer.Main.main(Main.java:215)
		at com.android.dx.command.Main.main(Main.java:106)
	9 errors; aborting

Why ?

**Comment by DrKLO** [comment]
Try to clean project and rebuild it.
